"""empty message

Revision ID: 58dfa9eab219
Revises: 70292a1a7d09
Create Date: 2022-08-07 13:15:28.970522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dfa9eab219'
down_revision = '70292a1a7d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pokemon', 'url')
    # ### end Alembic commands ###
