"""empty message

Revision ID: fab760184ea9
Revises: 58dfa9eab219
Create Date: 2022-08-14 12:24:28.491538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab760184ea9'
down_revision = '58dfa9eab219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('defense', sa.String(), nullable=True))
    op.drop_column('pokemon', 'defense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('defense', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pokemon', 'defense')
    # ### end Alembic commands ###
